### ISSUE TITLE
Support for multiple images/videos in the same post

### ISSUE THREAD

**Issue by onstash** [ericnishio/instagram-save#6]
Hey Eric Nishio,
Thanks for this wonderful package. I love how easy this is to use. Could you please tell me when/how a post with multiple images/videos would be supported? Thanks once again.

**Comment by ericnishio** [comment]
Thanks! That's a great question. I don't have any immediate plans to support multi-photo posts but it would definitely be a nice feature to have. Since the goal is to keep this library API key free, the image/video URLs would have to be scraped off the page.
